export enum Stacks {
  PUBLIC = 'STACK_PUBLIC',
  PRIVATE = 'STACK_PRIVATE',
  MODAL = 'MODAL',
}

export enum Routes {
  LOGIN = 'Login',
  HOME = 'Home',
  DRAWER = 'Drawer',
  RECOVER_PASSWORD = 'Recuperar_senha',
  ONBOARDING_NEW_REGISTER = 'Novo_cadastro',
  ONBOARDING_ADDRESS = 'Cadastrar_endereco',
  ONBOARDING_INFO_ENTERPRISE = 'Informacoes_pessoa_juridica',
  ONBOARDING_INFO_PERSON = 'Informacoes_pessoa_fisica',
  NEW_REQUEST_FREIGHT = 'Nova_Solicitar_frete',
  CARGO_REGISTER = 'Cadastro_da_carga',
  PACK_INFO = 'Dados_do_pacote',
  COLLECT_POINT = 'Ponto_de_coleta',
  POINT = 'Pontos',
  INVOICE = 'Faturas',
  INVOICE_DETAILS = 'Detalhes_da_fatura',
  FREIGHT_HISTORY = 'Historico_de_Fretes',
  FREIGHT_DETAIL = 'Detalhe_do_frete',
  COMPANY_DETAIL = 'Detalhe_da_compania',
  ESTIMAT_VEHICLE = 'Estimativa_Veiculo',
  ESTIMAT_SERVICE = 'Estimativa_Servico',
  ESTIMAT_PROPOSE_PRICE = 'Estimativa_Propor_Preco',
  PAYMENT = 'Pagamento_de_Frete',
  SERVICE_RECURRENCE = 'Recorrencia_de_servico',
  FREIGHT_CONCLUDE = 'Concluir_frete',
  FREIGHT_END = 'Finalizar_frete',
  FILTER = 'Filtro',
  PLACES_AUTO_COMPLETE = 'Places_Auto_complete',
  EDIT_PROFILE = 'Editar_perfil',
  EDIT_PROFILE_INFO = 'Editar_informacoes_do_perfil',
  EDIT_PROFILE_ADDRESS = 'Editar_endereço_do_perfil',
  EDIT_PROFILE_PASSWORD = 'Editar_senha_do_perfil',
}
