export enum REQUEST_FREIGHT_POINT {
  NO_POINT = -1,
  FIRST_POINT = 1,
  SECOND_POINT = 2,
}

export enum REQUEST_FREIGHT_PAYMENT {
  PAYMENT_MONEY = 0,
  PAYMENT_CARD = 1,
  PAYMENT_CREDIT_IN_ACCOUNT = 2,
}

export enum REQUEST_DEFAULT {
  ID_DEFAULT = -1,
}

export enum INDEX_TAB {
  FIRST = 0,
  SECOND = 1,
}
